# Generated by Django 6.1.1 on 2026-09-30 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Regular', 'Regular'), ('General', 'General'), ('Deep cleaning', 'Deep'), ('Move in / Move out', 'Move')], max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('cleaning_types', models.ManyToManyField(to='cleaning.cleaningtype')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('apartment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House')], max_length=20)),
                ('rooms', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in progress', 'Inprogress'), ('finished', 'Done'), ('canceled', 'Cancelled')], max_length=20)),
                ('notes', models.TextField()),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='cleaning.cleaner')),
                ('cleaning_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='cleaning.cleaningtype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='cleaning.property')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cleaner',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_cleaner_name'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('property_type', 'Apartment')), fields=('address', 'apartment_number'), name='unique_apartment_address'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('property_type', 'House')), fields=('address',), name='unique_house_address'),
        ),
        migrations.AddConstraint(
            model_name='cleaning',
            constraint=models.UniqueConstraint(fields=('date', 'property', 'cleaner'), name='unique_cleaning_combination'),
        ),
    ]
