# Generated by Django 6.1.1 on 2026-09-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_cleaningtype_cleaner_property_cleaning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in progress', 'In progress'), ('finished', 'Finished'), ('canceled', 'Canceled')], max_length=20),
        ),
    ]
