# Generated by Django 6.1.1 on 2026-10-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0003_alter_cleaning_notes_alter_cleaning_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('owner', 'Owner'), ('cleaner', 'Cleaner')], default='owner', max_length=20),
        ),
    ]
