# Generated by Django 6.1.1 on 2026-10-02 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cleaner',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
